# Generated by Django 2.0.5 on 2018-06-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0003_auto_20180611_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfp',
            name='slug',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
