# Generated by Django 2.0.5 on 2018-06-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0004_auto_20180611_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfp',
            name='duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cfp',
            name='type',
            field=models.IntegerField(choices=[(1, 'Talk'), (2, 'Workshop')], default=1),
        ),
    ]
