# Generated by Django 2.0.5 on 2018-08-07 09:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
        ('cfp', '0005_auto_20180629_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFPRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10, 'Maximum rating is 10'), django.core.validators.MinValueValidator(0, 'Minimum Rating is 10')])),
                ('cfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='cfp.Cfp')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cfprating',
            unique_together={('user', 'cfp')},
        ),
    ]
