# Generated by Django 2.0.5 on 2018-08-09 12:58

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0006_auto_20180807_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfprating',
            name='comment',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
