# Generated by Django 2.0.5 on 2018-08-09 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0007_cfprating_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfprating',
            name='mark',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10, 'Maximum rating is 10'), django.core.validators.MinValueValidator(1, 'Minimum Rating is 1')]),
        ),
    ]
