# Generated by Django 2.0.5 on 2018-08-10 18:59

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0008_auto_20180809_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfprating',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
