# Generated by Django 2.0.5 on 2018-08-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0009_auto_20180810_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfp',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False
        ),
    ]
