# Generated by Django 2.0.5 on 2018-10-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0010_cfp_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfp',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
