# Generated by Django 2.2.4 on 2019-08-27 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0011_speaker_conference'),
        ('cfp', '0012_cfp_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfp',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='speaker.Speaker'),
        ),
    ]
