# Generated by Django 2.0.5 on 2018-06-22 15:29

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('coc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', markdownx.models.MarkdownxField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
