# Generated by Django 2.0.5 on 2018-06-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coc', '0002_response_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseguide',
            name='slug',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
