# Generated by Django 2.0.5 on 2018-05-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='from_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='to_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
