# Generated by Django 2.0.5 on 2018-08-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20180604_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='type',
            field=models.IntegerField(choices=[(0, 'Talk'), (1, 'Workshop'), (2, 'Keynote')], default=0),
        ),
    ]
