# Generated by Django 2.1.7 on 2019-03-21 19:07

from django.db import migrations, models
import django.db.models.deletion
import pyconbalkan.conference.models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0008_auto_20190303_1800'),
        ('timetable', '0003_auto_20180803_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='conference',
            field=models.ForeignKey(default=pyconbalkan.conference.models._get_default_conference, on_delete=django.db.models.deletion.CASCADE, to='conference.Conference'),
        ),
    ]
