# Generated by Django 2.2.4 on 2019-08-27 20:44

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('timetable', '0005_auto_20190827_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
