# Generated by Django 2.2.4 on 2019-08-27 22:47

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Presentation = apps.get_model("timetable", "Presentation")
    Presentation.objects.filter(type=0).update(type=10)  # TALK = 10  # 0
    Presentation.objects.filter(type=1).update(type=15)  # WORKSHOP = 15  # 1
    Presentation.objects.filter(type=2).update(type=5)  # KEYNOTE = 5  # 2


def reverse_func(apps, schema_editor):
    Presentation = apps.get_model("timetable", "Presentation")
    Presentation.objects.filter(type=10).update(type=0)  # TALK = 10  # 0
    Presentation.objects.filter(type=15).update(type=1)  # WORKSHOP = 15  # 1
    Presentation.objects.filter(type=5).update(type=2)  # KEYNOTE = 5  # 2


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0006_auto_20190827_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='type',
            field=models.IntegerField(choices=[(10, 'Talk'), (15, 'Workshop'), (5, 'Keynote')], default=10),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
