# Generated by Django 2.2.4 on 2019-09-12 18:47

from django.db import migrations, models
import django.db.models.deletion
import pyconbalkan.conference.models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0009_remove_conference_timetable_pdf'),
        ('timetable', '0007_auto_20190827_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='timetable',
        ),
        migrations.AddField(
            model_name='room',
            name='conference',
            field=models.ForeignKey(default=pyconbalkan.conference.models._get_default_conference, on_delete=django.db.models.deletion.CASCADE, to='conference.Conference'),
        ),
        migrations.AddField(
            model_name='room',
            name='sort_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='conference',
            field=models.ForeignKey(default=pyconbalkan.conference.models._get_default_conference, on_delete=django.db.models.deletion.CASCADE, to='conference.Conference'),
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
