# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-06 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='full_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='personal_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='job',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
