# Generated by Django 2.0.5 on 2018-05-18 10:23

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0002_auto_20180506_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='biography',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
