# Generated by Django 2.0.5 on 2018-06-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0002_auto_20180506_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakerphoto',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='speakers/profile_picture'),
        ),
    ]
