# Generated by Django 2.0.5 on 2018-06-10 10:53

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0003_auto_20180603_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='speaker',
            name='keynote',
            field=models.BooleanField(default=False),
        ),
    ]
