# Generated by Django 2.0.5 on 2018-06-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0005_speaker_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='slug',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
