# Generated by Django 2.0.5 on 2018-06-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0007_speaker_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='talk_excerpt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
