# Generated by Django 2.0.5 on 2018-06-20 06:07

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0007_speaker_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='talk_excerpt',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
