# Generated by Django 2.0.5 on 2018-06-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0007_speaker_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
