# Generated by Django 2.0.5 on 2018-08-01 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0008_person_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speaker',
            options={'ordering': ('full_name',)},
        ),
    ]
