# Generated by Django 2.2.4 on 2019-08-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0011_speaker_conference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='active',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='conference',
        ),
    ]
