# Generated by Django 2.1.7 on 2019-05-17 13:07

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', markdownx.models.MarkdownxField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
