# Generated by Django 2.0.5 on 2018-06-10 16:08
import random
import string

from django.db import migrations, models
from slugify import slugify


def create_slug_in_volunteer(apps, schema_editor):
    # Create slug in Volunteer
    Volunteer = apps.get_model("organizers", "Volunteer")
    for volunteer in Volunteer.objects.all():
        volunteer.slug = '{}-{}'.format(slugify(volunteer.full_name), ''.join(random.choices(string.ascii_uppercase + string.digits, k=4)))
        volunteer.save()

def remove_slug(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0003_auto_20180603_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='slug',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(create_slug_in_volunteer, remove_slug)
    ]
