# Generated by Django 2.0.5 on 2018-06-10 16:08
import random
import string

from django.db import migrations, models
from slugify import slugify

import pyconbalkan.core.models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Volunteer = apps.get_model("organizers", "Volunteer")
    for volunteer in Volunteer.objects.all():
        volunteer.slug = slugify(volunteer.full_name) + '-' +''.join(random.choices(string.ascii_uppercase + string.digits, k=4))
        volunteer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0003_auto_20180603_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='slug',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(forwards_func)
    ]
