# Generated by Django 2.0.5 on 2018-06-11 12:03

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0005_auto_20180610_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, default=''),
        ),
    ]
