# Generated by Django 2.0.5 on 2018-06-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0007_volunteer_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='weight',
            field=models.IntegerField(unique=True),
        ),
    ]
