# Generated by Django 2.0.5 on 2018-06-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0008_auto_20180611_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='weight',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
