# Generated by Django 2.0.5 on 2018-06-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0009_auto_20180613_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
