# Generated by Django 2.0.5 on 2018-08-01 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0010_person_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='weight',
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer', to=settings.AUTH_USER_MODEL),
        ),
    ]
