# Generated by Django 2.0.5 on 2018-08-01 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0011_auto_20180801_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ('full_name',)},
        ),
    ]
