# Generated by Django 2.0.5 on 2018-05-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_packageoption_sponsorshippackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorshippackage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
