# Generated by Django 2.0.5 on 2018-08-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0005_auto_20180804_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsoring',
            name='organization_type',
            field=models.IntegerField(choices=[(1, 'For - profit corporation'), (2, 'Foundation / Non profit')], default=1),
        ),
    ]
