# Generated by Django 2.0.5 on 2018-08-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0007_sponsoring_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsoring',
            name='organization',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sponsoring',
            name='organization_type',
            field=models.IntegerField(choices=[(1, 'Profit Corporation'), (2, 'Foundation / Non profit')], default=1),
        ),
    ]
