# Generated by Django 2.1.7 on 2019-03-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0008_auto_20180811_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(upload_to='sponsors/logo'),
        ),
    ]
