# Generated by Django 2.1.7 on 2019-02-27 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0006_conference_timetable_pdf'),
        ('sponsors', '0008_auto_20180811_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorConference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Keystone', 'keystone'), ('Platinum', 'platinum'), ('Gold', 'gold'), ('Silver', 'silver'), ('Partner', 'partner')], max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='sponsorconference',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsors.Sponsor'),
        ),
        migrations.AddField(
            model_name='sponsorconference',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Conference'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='conferences',
            field=models.ManyToManyField(through='sponsors.SponsorConference', to='conference.Conference'),
        ),
    ]
