# Generated by Django 2.1.7 on 2019-03-03 14:42

from django.db import migrations, models
import django.db.models.deletion
import pyconbalkan.conference.abstractions


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0007_auto_20190227_0738'),
        ('sponsors', '0009_auto_20190303_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='conference',
            field=models.ForeignKey(default=pyconbalkan.conference.models._get_default_conference, on_delete=django.db.models.deletion.CASCADE, to='conference.Conference'),
        ),
    ]
