# Generated by Django 2.1.7 on 2019-02-27 06:46

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Sponsor = apps.get_model("sponsors", "Sponsor")
    SponsorConference = apps.get_model("sponsors", "SponsorConference")
    Conference = apps.get_model("conference", "Conference")
    first_conference = Conference.objects.first()

    for sponsor in Sponsor.objects.all():
        SponsorConference.objects.create(
            sponsor=sponsor,
            level=sponsor.level,
            conference=first_conference
        )


def backwards_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0009_auto_20190227_0645'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_code=backwards_func),
        migrations.RemoveField(
            model_name='sponsor',
            name='level',
        ),
    ]
