# Generated by Django 2.1.7 on 2019-03-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0010_sponsor_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='supported_by',
            field=models.BooleanField(default=False),
        ),
    ]
