# Generated by Django 2.1.7 on 2019-03-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0010_sponsor_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='sidebar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='url',
            field=models.URLField(max_length=256, null=True),
        ),
    ]
