# Generated by Django 2.1.7 on 2019-03-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0011_auto_20190321_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.FileField(upload_to='sponsors/logo'),
        ),
    ]
