# Generated by Django 2.1.7 on 2019-03-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0011_sponsor_supported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='url',
            field=models.URLField(max_length=256, null=True),
        ),
    ]
