# Generated by Django 2.1.7 on 2019-03-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0013_auto_20190322_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
