# Generated by Django 2.1.7 on 2019-02-27 06:45

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
