# Generated by Django 2.0.5 on 2018-06-11 19:54
import random
import string

from django.db import migrations, models
from slugify import slugify


def create_slug_in_post(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Post = apps.get_model("news", "Post")
    for post in Post.objects.all():
        post.slug = slugify(post.title)
        post.save()


def remove_slug(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180604_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(create_slug_in_post, remove_slug)
    ]
