# Generated by Django 2.0.5 on 2018-07-27 18:13

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('news', '0005_auto_20180611_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
