# Generated by Django 2.0.5 on 2018-08-01 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_post_keywords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published_date',)},
        ),
    ]
