# Generated by Django 2.1.7 on 2019-03-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_post_conference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='conference',
        ),
    ]
