# Generated by Django 2.2.4 on 2019-09-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_post_front_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='front_page',
            field=models.BooleanField(default=False, verbose_name='Promote news article to frontpage'),
        ),
    ]
