# Generated by Django 2.0.5 on 2018-07-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_mission_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='meta_author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='meta_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
