# Generated by Django 2.0.5 on 2018-08-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_auto_20180710_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='meta_author',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='meta_description',
        ),
        migrations.AddField(
            model_name='conference',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='tickets',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
