# Generated by Django 2.0.5 on 2018-08-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_auto_20180802_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='sponsor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
