# Generated by Django 2.1.2 on 2018-11-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_auto_20180804_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='timetable_pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
