# Generated by Django 2.1.2 on 2019-03-03 18:00

from django.db import migrations, models
import django.db.models.deletion
import pyconbalkan.conference.models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0007_auto_20190227_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdown',
            name='conference',
            field=models.ForeignKey(default=pyconbalkan.conference.models._get_default_conference, on_delete=django.db.models.deletion.CASCADE, to='conference.Conference'),
        ),
        migrations.AddField(
            model_name='missionstatement',
            name='conference',
            field=models.ForeignKey(default=pyconbalkan.conference.models._get_default_conference, on_delete=django.db.models.deletion.CASCADE, to='conference.Conference'),
        ),
    ]
