# Generated by Django 2.2.4 on 2019-09-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0010_conference_conference_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='workshop_application_embed_code',
            field=models.TextField(blank=True, null=True, verbose_name='Embed code that is usually an iframe from google docs'),
        ),
    ]
